<?php

namespace dasturchiuz\chatroom;

use dasturchiuz\chatroom\models\Messages;
use yii\data\ActiveDataProvider;
use dasturchiuz\chatroom\ChatRoomAsset;

class MessageReadAdmin extends \yii\base\Widget
{
    public $userID;
    public $clientID;
    public $chatRoom;
    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        ChatRoomAsset::register($this->getView());

        $chats=Messages::find()->where(['or',
            ['sender_id'=>$this->userID,'sender_id'=>$this->clientID, ],
            ['receiver_id'=>$this->userID,'receiver_id'=>$this->clientID, ]
        ])->andWhere(['chatroom_id'=>$this->chatRoom]);
        $dataProvider = new ActiveDataProvider([
            'query' => $chats,
            'pagination' => [
                'pageSize'=>10,

            ]
        ]);

        $pagesize = $dataProvider->pagination->pageSize;// it will give Per Page data.

        $total = $dataProvider->totalCount; //total records // 15
        if(!\Yii::$app->getRequest()->getQueryParam('page')){
            $dataProvider->pagination->page=(int) (($total + $pagesize - 1) / $pagesize)-1;
        }


        $profile=\app\models\Profile::findOne($this->clientID);
        if(empty($profile)){

            return $this->render('empty');
        }
        $modelMessage=new Messages();
        return $this->render('messagereadadmin', ['dataProvider' => $dataProvider, 'user_id'=>$this->userID, 'clientID'=>$this->clientID, 'profile'=>$profile, 'modelMessage'=>$modelMessage, 'chatRoom'=>$this->chatRoom]);
    }
}
